name: Continuous Delivery - Wait4Rez LUA

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: windows-latest
    env:
      BundleFileName: "wait4rez.zip"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Create Bundle  
      shell: bash
      run: |
        # Pack files
        mkdir wait4rez
        cp *.lua /wait4rez
        7z a -tzip $BundleFileName wait4rez/*.lua
        7z a -tzip $BundleFileName utils/*.lua

    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
        files: "*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# https://github.com/marketplace/actions/easy-zip-files        